//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.09 at 06:31:44 AM CEST 
//


package com.example.ws.gekon;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.w3._2005._05.xmlmime.Base64Binary;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gekon package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MERGETIFFRequestElement_QNAME = new QName("urn:Gekon", "MERGE_TIFFRequestElement");
    private final static QName _MERGETIFFReturnElement_QNAME = new QName("urn:Gekon", "MERGE_TIFFReturnElement");
    private final static QName _InputSetRowDocFormat_QNAME = new QName("urn:Gekon", "doc_format");
    private final static QName _InputSetRowLocation_QNAME = new QName("urn:Gekon", "location");
    private final static QName _InputSetRowOptions_QNAME = new QName("urn:Gekon", "options");
    private final static QName _InputSetRowContent_QNAME = new QName("urn:Gekon", "content");
    private final static QName _MERGETIFFReturnPageCount_QNAME = new QName("urn:Gekon", "page_count");
    private final static QName _MERGETIFFReturnErrorCode_QNAME = new QName("urn:Gekon", "error_code");
    private final static QName _MERGETIFFReturnErrorDesc_QNAME = new QName("urn:Gekon", "error_desc");
    private final static QName _MERGETIFFQueryDocuments_QNAME = new QName("urn:Gekon", "documents");
    private final static QName _MERGETIFFQueryStorageType_QNAME = new QName("urn:Gekon", "storage_type");
    private final static QName _MERGETIFFQueryApplId_QNAME = new QName("urn:Gekon", "appl_id");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gekon
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MERGETIFFQuery }
     * 
     */
    public MERGETIFFQuery createMERGETIFFQuery() {
        return new MERGETIFFQuery();
    }

    /**
     * Create an instance of {@link MERGETIFFReturn }
     * 
     */
    public MERGETIFFReturn createMERGETIFFReturn() {
        return new MERGETIFFReturn();
    }

    /**
     * Create an instance of {@link InputSet }
     * 
     */
    public InputSet createInputSet() {
        return new InputSet();
    }

    /**
     * Create an instance of {@link InputSetRow }
     * 
     */
    public InputSetRow createInputSetRow() {
        return new InputSetRow();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MERGETIFFQuery }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MERGETIFFQuery }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "MERGE_TIFFRequestElement")
    public JAXBElement<MERGETIFFQuery> createMERGETIFFRequestElement(MERGETIFFQuery value) {
        return new JAXBElement<MERGETIFFQuery>(_MERGETIFFRequestElement_QNAME, MERGETIFFQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MERGETIFFReturn }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MERGETIFFReturn }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "MERGE_TIFFReturnElement")
    public JAXBElement<MERGETIFFReturn> createMERGETIFFReturnElement(MERGETIFFReturn value) {
        return new JAXBElement<MERGETIFFReturn>(_MERGETIFFReturnElement_QNAME, MERGETIFFReturn.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "doc_format", scope = InputSetRow.class)
    public JAXBElement<String> createInputSetRowDocFormat(String value) {
        return new JAXBElement<String>(_InputSetRowDocFormat_QNAME, String.class, InputSetRow.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "location", scope = InputSetRow.class)
    public JAXBElement<String> createInputSetRowLocation(String value) {
        return new JAXBElement<String>(_InputSetRowLocation_QNAME, String.class, InputSetRow.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "options", scope = InputSetRow.class)
    public JAXBElement<String> createInputSetRowOptions(String value) {
        return new JAXBElement<String>(_InputSetRowOptions_QNAME, String.class, InputSetRow.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Base64Binary }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Base64Binary }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "content", scope = InputSetRow.class)
    public JAXBElement<Base64Binary> createInputSetRowContent(Base64Binary value) {
        return new JAXBElement<Base64Binary>(_InputSetRowContent_QNAME, Base64Binary.class, InputSetRow.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "doc_format", scope = MERGETIFFReturn.class)
    public JAXBElement<String> createMERGETIFFReturnDocFormat(String value) {
        return new JAXBElement<String>(_InputSetRowDocFormat_QNAME, String.class, MERGETIFFReturn.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "location", scope = MERGETIFFReturn.class)
    public JAXBElement<String> createMERGETIFFReturnLocation(String value) {
        return new JAXBElement<String>(_InputSetRowLocation_QNAME, String.class, MERGETIFFReturn.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "page_count", scope = MERGETIFFReturn.class)
    public JAXBElement<Long> createMERGETIFFReturnPageCount(Long value) {
        return new JAXBElement<Long>(_MERGETIFFReturnPageCount_QNAME, Long.class, MERGETIFFReturn.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Base64Binary }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Base64Binary }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "content", scope = MERGETIFFReturn.class)
    public JAXBElement<Base64Binary> createMERGETIFFReturnContent(Base64Binary value) {
        return new JAXBElement<Base64Binary>(_InputSetRowContent_QNAME, Base64Binary.class, MERGETIFFReturn.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "error_code", scope = MERGETIFFReturn.class)
    public JAXBElement<String> createMERGETIFFReturnErrorCode(String value) {
        return new JAXBElement<String>(_MERGETIFFReturnErrorCode_QNAME, String.class, MERGETIFFReturn.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "error_desc", scope = MERGETIFFReturn.class)
    public JAXBElement<String> createMERGETIFFReturnErrorDesc(String value) {
        return new JAXBElement<String>(_MERGETIFFReturnErrorDesc_QNAME, String.class, MERGETIFFReturn.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputSet }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InputSet }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "documents", scope = MERGETIFFQuery.class)
    public JAXBElement<InputSet> createMERGETIFFQueryDocuments(InputSet value) {
        return new JAXBElement<InputSet>(_MERGETIFFQueryDocuments_QNAME, InputSet.class, MERGETIFFQuery.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "storage_type", scope = MERGETIFFQuery.class)
    public JAXBElement<String> createMERGETIFFQueryStorageType(String value) {
        return new JAXBElement<String>(_MERGETIFFQueryStorageType_QNAME, String.class, MERGETIFFQuery.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:Gekon", name = "appl_id", scope = MERGETIFFQuery.class)
    public JAXBElement<String> createMERGETIFFQueryApplId(String value) {
        return new JAXBElement<String>(_MERGETIFFQueryApplId_QNAME, String.class, MERGETIFFQuery.class, value);
    }

}
